(function(){
  window.LocalesExtra = window.LocalesExtra || {};
  // Helper: minimal, accurate dictionaries; missing keys fall back to English
  
  window.LocalesExtra['it'] = {
    'title.app':'Ultimate Stopwatch',
    'action.settings':'Impostazioni','action.close':'Chiudi','action.cancel':'Annulla','action.create':'Crea','action.save':'Salva','action.update':'Aggiorna','action.apply':'Applica','action.proceed':'Procedi','action.resume':'Riprendi','action.pause':'Pausa','action.stop':'Stop','action.reset':'Reimposta','action.start':'Avvia','action.next':'Avanti','action.calculate':'Calcola','action.chooseImage':'Scegli immagine',
    'header.stopwatch':'Cronometro',
    'home.empty1':'Nessun progetto.','home.empty2':'Crea un progetto per iniziare!',
    'folder.empty1':'Nessun risultato.','folder.empty2':'Avvia la misurazione per crearne uno!','folder.result':'risultato','folder.results':'risultati',
    'settings.language':'Lingua','settings.units':'Unità','settings.metric':'Metrico (ms, s)','settings.imperial':'Imperiale','settings.currency':'Valuta','settings.power':'Alimentazione','settings.keepAwake':'Mantieni schermo attivo durante la ricarica','settings.timeDisplay':'Visualizzazione del tempo','settings.hms':'Ore:Minuti:Secondi','settings.ms':'Minuti:Secondi','settings.precision':'Precisione','settings.showHundredths':'Mostra centesimi','settings.reOrContinue':'Rimisura o continua da dove eri rimasto','settings.uploadChangeImage':'Carica/Cambia immagine','settings.projectSettings':'Impostazioni del progetto corrente.',
    'theme.title':'Personalizzazione tema','theme.preset':'Palette predefinite','theme.customColors':'Colori personalizzati','theme.background':'Sfondo','theme.accent':'Evidenza','theme.text':'Testo','theme.border':'Bordo','theme.applyCustom':'Applica tema personalizzato',
    'color.preset':'Colori predefiniti','color.custom':'Colore personalizzato',
    'menu.chooseProjectColor':'Scegli colore progetto','menu.chooseProjectTextColor':'Scegli colore testo progetto','menu.delete':'Elimina',
    'confirm.deleteProject':'Eliminare questo progetto e tutti i risultati?','confirm.deleteResult':'Eliminare questo risultato?','confirm.stopSession':'Interrompere la sessione corrente?',
    'tooltip.newProject':'Nuovo progetto','tooltip.startStopwatch':'Avvia cronometro',
    'stopwatch.laps':'Giri','stopwatch.avg':'Media','stopwatch.avgLap':'Giro medio','stopwatch.lap':'Giro','stopwatch.allLaps':'Tutti i giri',
    'calc.title':'Calcola','calc.tab.quantity':'Quantità','calc.tab.time':'Tempo','calc.tab.price':'Prezzo','calc.numberOfItems':'Numero di pezzi','calc.estimatedTotalTime':'Tempo totale stimato','calc.duration':'Durata','calc.estimatedQuantity':'Quantità stimata','calc.hourlyWage':'Paga oraria','calc.pricePerPiece':'Prezzo per pezzo',
    'dialog.updateImageTitle':'Aggiorna immagine','resultDetail.totalTime':'Tempo totale',
    'error.wakeLockUnsupported':'Screen Wake Lock non è supportato da questo browser.','error.saveFailed':'Salvataggio non riuscito: memoria piena o dati troppo grandi.','error.projectNotFound':'Progetto non trovato. Potrebbe essere stato eliminato.',
    'label.h':'h','label.m':'m','label.s':'s','currency.euro':'Euro (€)','currency.usd':'Dollaro USA ($)','currency.gbp':'Sterlina (£)'
  };

  window.LocalesExtra['de'] = {
    'title.app':'Ultimate Stopwatch',
    'action.settings':'Einstellungen','action.close':'Schließen','action.cancel':'Abbrechen','action.create':'Erstellen','action.save':'Speichern','action.update':'Aktualisieren','action.apply':'Anwenden','action.proceed':'Fortfahren','action.resume':'Fortsetzen','action.pause':'Pause','action.stop':'Stopp','action.reset':'Zurücksetzen','action.start':'Start','action.next':'Weiter','action.calculate':'Berechnen','action.chooseImage':'Bild auswählen',
    'header.stopwatch':'Stoppuhr',
    'home.empty1':'Noch keine Projekte.','home.empty2':'Erstelle eines, um zu starten!',
    'folder.empty1':'Noch keine Ergebnisse.','folder.empty2':'Starte die Messung, um eines zu erstellen!','folder.result':'Ergebnis','folder.results':'Ergebnisse',
    'settings.language':'Sprache','settings.units':'Einheiten','settings.metric':'Metrisch (ms, s)','settings.imperial':'Imperial','settings.currency':'Währung','settings.power':'Strom','settings.keepAwake':'Bildschirm beim Laden eingeschaltet lassen','settings.timeDisplay':'Zeitanzeige','settings.hms':'Stunden:Minuten:Sekunden','settings.ms':'Minuten:Sekunden','settings.precision':'Genauigkeit','settings.showHundredths':'Hundertstel anzeigen','settings.reOrContinue':'Neu messen oder weitermachen','settings.uploadChangeImage':'Bild hochladen/ändern','settings.projectSettings':'Projekteinstellungen für das aktuelle Projekt.',
    'theme.title':'Design anpassen','theme.preset':'Voreingestellte Paletten','theme.customColors':'Benutzerdefinierte Farben','theme.background':'Hintergrund','theme.accent':'Akzent','theme.text':'Text','theme.border':'Rahmen','theme.applyCustom':'Benutzerdefiniertes Design anwenden',
    'color.preset':'Voreingestellte Farben','color.custom':'Benutzerdefinierte Farbe',
    'menu.chooseProjectColor':'Projektfarbe wählen','menu.chooseProjectTextColor':'Projekttextfarbe wählen','menu.delete':'Löschen',
    'confirm.deleteProject':'Dieses Projekt und alle Ergebnisse löschen?','confirm.deleteResult':'Dieses Ergebnis löschen?','confirm.stopSession':'Aktuelle Sitzung stoppen?',
    'tooltip.newProject':'Neues Projekt','tooltip.startStopwatch':'Stoppuhr starten',
    'stopwatch.laps':'Runden','stopwatch.avg':'Durchschn.','stopwatch.avgLap':'Durchschn. Runde','stopwatch.lap':'Runde','stopwatch.allLaps':'Alle Runden',
    'calc.title':'Berechnen','calc.tab.quantity':'Menge','calc.tab.time':'Zeit','calc.tab.price':'Preis','calc.numberOfItems':'Anzahl der Teile','calc.estimatedTotalTime':'Geschätzte Gesamtzeit','calc.duration':'Dauer','calc.estimatedQuantity':'Geschätzte Menge','calc.hourlyWage':'Stundenlohn','calc.pricePerPiece':'Preis pro Stück',
    'dialog.updateImageTitle':'Bild aktualisieren','resultDetail.totalTime':'Gesamtzeit',
    'error.wakeLockUnsupported':'Wake Lock wird von diesem Browser nicht unterstützt.','error.saveFailed':'Speichern fehlgeschlagen: Speicher voll oder Daten zu groß.','error.projectNotFound':'Projekt nicht gefunden. Möglicherweise gelöscht.',
    'label.h':'h','label.m':'m','label.s':'s','currency.euro':'Euro (€)','currency.usd':'US-Dollar ($)','currency.gbp':'Pfund (£)'
  };

  window.LocalesExtra['es'] = {
    'title.app':'Ultimate Stopwatch',
    'action.settings':'Configuración','action.close':'Cerrar','action.cancel':'Cancelar','action.create':'Crear','action.save':'Guardar','action.update':'Actualizar','action.apply':'Aplicar','action.proceed':'Continuar','action.resume':'Reanudar','action.pause':'Pausa','action.stop':'Detener','action.reset':'Restablecer','action.start':'Iniciar','action.next':'Siguiente','action.calculate':'Calcular','action.chooseImage':'Elegir imagen',
    'header.stopwatch':'Cronómetro','home.empty1':'Aún no hay proyectos.','home.empty2':'¡Crea uno para empezar!','folder.empty1':'Aún no hay resultados.','folder.empty2':'Inicia la medición para crear uno!','folder.result':'resultado','folder.results':'resultados',
    'settings.language':'Idioma','settings.units':'Unidades','settings.metric':'Métrico (ms, s)','settings.imperial':'Imperial','settings.currency':'Moneda','settings.power':'Energía','settings.keepAwake':'Mantener la pantalla activa durante la carga','settings.timeDisplay':'Formato de tiempo','settings.hms':'Horas:Minutos:Segundos','settings.ms':'Minutos:Segundos','settings.precision':'Precisión','settings.showHundredths':'Mostrar centésimas','settings.reOrContinue':'Volver a medir o continuar donde lo dejaste','settings.uploadChangeImage':'Subir/Cambiar imagen','settings.projectSettings':'Ajustes del proyecto actual.',
    'theme.title':'Personalización del tema','theme.preset':'Paletas predefinidas','theme.customColors':'Colores personalizados','theme.background':'Fondo','theme.accent':'Acento','theme.text':'Texto','theme.border':'Borde','theme.applyCustom':'Aplicar tema personalizado',
    'color.preset':'Colores predefinidos','color.custom':'Color personalizado','menu.chooseProjectColor':'Elegir color del proyecto','menu.chooseProjectTextColor':'Elegir color del texto del proyecto','menu.delete':'Eliminar','confirm.deleteProject':'¿Eliminar este proyecto y todos sus resultados?','confirm.deleteResult':'¿Eliminar este resultado?','confirm.stopSession':'¿Detener la sesión actual?',
    'tooltip.newProject':'Nuevo proyecto','tooltip.startStopwatch':'Iniciar cronómetro','stopwatch.laps':'Vueltas','stopwatch.avg':'Prom.','stopwatch.avgLap':'Vuelta prom.','stopwatch.lap':'Vuelta','stopwatch.allLaps':'Todas las vueltas','calc.title':'Calcular','calc.tab.quantity':'Cantidad','calc.tab.time':'Tiempo','calc.tab.price':'Precio','calc.numberOfItems':'Número de piezas','calc.estimatedTotalTime':'Tiempo total estimado','calc.duration':'Duración','calc.estimatedQuantity':'Cantidad estimada','calc.hourlyWage':'Salario por hora','calc.pricePerPiece':'Precio por pieza','dialog.updateImageTitle':'Actualizar imagen','resultDetail.totalTime':'Tiempo total','error.wakeLockUnsupported':'Wake Lock no está soportado por este navegador.','error.saveFailed':'Guardado fallido: almacenamiento lleno o datos demasiado grandes.','error.projectNotFound':'Proyecto no encontrado. Puede que se haya eliminado.','label.h':'h','label.m':'m','label.s':'s','currency.euro':'Euro (€)','currency.usd':'Dólar estadounidense ($)','currency.gbp':'Libra (£)'
  };

  window.LocalesExtra['pt-BR'] = {
    'title.app':'Ultimate Stopwatch','action.settings':'Configurações','action.close':'Fechar','action.cancel':'Cancelar','action.create':'Criar','action.save':'Salvar','action.update':'Atualizar','action.apply':'Aplicar','action.proceed':'Prosseguir','action.resume':'Retomar','action.pause':'Pausar','action.stop':'Parar','action.reset':'Redefinir','action.start':'Iniciar','action.next':'Próximo','action.calculate':'Calcular','action.chooseImage':'Escolher imagem','header.stopwatch':'Cronômetro','home.empty1':'Ainda não há projetos.','home.empty2':'Crie um para começar!','folder.empty1':'Ainda não há resultados.','folder.empty2':'Inicie a medição para criar um!','folder.result':'resultado','folder.results':'resultados','settings.language':'Idioma','settings.units':'Unidades','settings.metric':'Métrico (ms, s)','settings.imperial':'Imperial','settings.currency':'Moeda','settings.power':'Energia','settings.keepAwake':'Manter a tela ativa durante o carregamento','settings.timeDisplay':'Exibição de tempo','settings.hms':'Horas:Minutos:Segundos','settings.ms':'Minutos:Segundos','settings.precision':'Precisão','settings.showHundredths':'Mostrar centésimos','settings.reOrContinue':'Medir novamente ou continuar de onde parou','settings.uploadChangeImage':'Enviar/Alterar imagem','settings.projectSettings':'Configurações do projeto atual.','theme.title':'Personalização do tema','theme.preset':'Paletas predefinidas','theme.customColors':'Cores personalizadas','theme.background':'Fundo','theme.accent':'Realce','theme.text':'Texto','theme.border':'Borda','theme.applyCustom':'Aplicar tema personalizado','color.preset':'Cores predefinidas','color.custom':'Cor personalizada','menu.chooseProjectColor':'Escolher cor do projeto','menu.chooseProjectTextColor':'Escolher cor do texto do projeto','menu.delete':'Excluir','confirm.deleteProject':'Excluir este projeto e todos os resultados?','confirm.deleteResult':'Excluir este resultado?','confirm.stopSession':'Parar a sessão atual?','tooltip.newProject':'Novo projeto','tooltip.startStopwatch':'Iniciar cronômetro','stopwatch.laps':'Voltas','stopwatch.avg':'Média','stopwatch.avgLap':'Volta média','stopwatch.lap':'Volta','stopwatch.allLaps':'Todas as voltas','dialog.updateImageTitle':'Atualizar imagem','resultDetail.totalTime':'Tempo total','label.h':'h','label.m':'m','label.s':'s'
  };

  window.LocalesExtra['pt'] = {
    'title.app':'Ultimate Stopwatch','action.settings':'Definições','action.close':'Fechar','action.cancel':'Cancelar','action.create':'Criar','action.save':'Guardar','action.update':'Atualizar','action.apply':'Aplicar','action.proceed':'Continuar','action.resume':'Retomar','action.pause':'Pausa','action.stop':'Parar','action.reset':'Repor','action.start':'Iniciar','action.next':'Seguinte','action.calculate':'Calcular','action.chooseImage':'Escolher imagem','header.stopwatch':'Cronómetro','home.empty1':'Ainda não há projetos.','home.empty2':'Crie um para começar!','folder.empty1':'Ainda não há resultados.','folder.empty2':'Inicie a medição para criar um!','folder.result':'resultado','folder.results':'resultados','settings.language':'Idioma','settings.units':'Unidades','settings.metric':'Métrico (ms, s)','settings.imperial':'Imperial','settings.currency':'Moeda','settings.power':'Energia','settings.keepAwake':'Manter o ecrã ligado durante o carregamento','settings.timeDisplay':'Apresentação do tempo','settings.hms':'Horas:Minutos:Segundos','settings.ms':'Minutos:Segundos','settings.precision':'Precisão','settings.showHundredths':'Mostrar centésimos','settings.reOrContinue':'Medir novamente ou continuar onde parou','settings.uploadChangeImage':'Carregar/Alterar imagem','settings.projectSettings':'Definições do projeto atual.','theme.title':'Personalização do tema','theme.preset':'Paletas predefinidas','theme.customColors':'Cores personalizadas','theme.background':'Fundo','theme.accent':'Destaque','theme.text':'Texto','theme.border':'Contorno','theme.applyCustom':'Aplicar tema personalizado','color.preset':'Cores predefinidas','color.custom':'Cor personalizada','menu.chooseProjectColor':'Escolher cor do projeto','menu.chooseProjectTextColor':'Escolher cor do texto do projeto','menu.delete':'Eliminar','confirm.deleteProject':'Eliminar este projeto e todos os resultados?','confirm.deleteResult':'Eliminar este resultado?','confirm.stopSession':'Parar a sessão atual?','tooltip.newProject':'Novo projeto','tooltip.startStopwatch':'Iniciar cronómetro','stopwatch.laps':'Voltas','stopwatch.avg':'Méd.','stopwatch.avgLap':'Volta média','stopwatch.lap':'Volta','stopwatch.allLaps':'Todas as voltas','dialog.updateImageTitle':'Atualizar imagem','resultDetail.totalTime':'Tempo total','label.h':'h','label.m':'m','label.s':'s'
  };

  window.LocalesExtra['fr'] = {
    'title.app':'Ultimate Stopwatch','action.settings':'Paramètres','action.close':'Fermer','action.cancel':'Annuler','action.create':'Créer','action.save':'Enregistrer','action.update':'Mettre à jour','action.apply':'Appliquer','action.proceed':'Continuer','action.resume':'Reprendre','action.pause':'Pause','action.stop':'Arrêter','action.reset':'Réinitialiser','action.start':'Démarrer','action.next':'Suivant','action.calculate':'Calculer','action.chooseImage':'Choisir une image','header.stopwatch':'Chronomètre','home.empty1':'Aucun projet pour le moment.','home.empty2':'Créez-en un pour commencer !','folder.empty1':'Aucun résultat pour le moment.','folder.empty2':'Lancez une mesure pour en créer un !','folder.result':'résultat','folder.results':'résultats','settings.language':'Langue','settings.units':'Unités','settings.metric':'Métrique (ms, s)','settings.imperial':'Impérial','settings.currency':'Devise','settings.power':'Alimentation','settings.keepAwake':'Garder l’écran actif lors de la charge','settings.timeDisplay':'Affichage du temps','settings.hms':'Heures:Minutes:Secondes','settings.ms':'Minutes:Secondes','settings.precision':'Précision','settings.showHundredths':'Afficher les centièmes','settings.reOrContinue':'Remesurer ou continuer là où vous vous êtes arrêté','settings.uploadChangeImage':'Téléverser/Changer l’image','settings.projectSettings':'Paramètres du projet en cours.','theme.title':'Personnalisation du thème','theme.preset':'Palettes prédéfinies','theme.customColors':'Couleurs personnalisées','theme.background':'Arrière-plan','theme.accent':'Accent','theme.text':'Texte','theme.border':'Bordure','theme.applyCustom':'Appliquer le thème personnalisé','color.preset':'Couleurs prédéfinies','color.custom':'Couleur personnalisée','menu.chooseProjectColor':'Choisir la couleur du projet','menu.chooseProjectTextColor':'Choisir la couleur du texte du projet','menu.delete':'Supprimer','confirm.deleteProject':'Supprimer ce projet et tous ses résultats ?','confirm.deleteResult':'Supprimer ce résultat ?','confirm.stopSession':'Arrêter la session en cours ?','tooltip.newProject':'Nouveau projet','tooltip.startStopwatch':'Démarrer le chronomètre','stopwatch.laps':'Tours','stopwatch.avg':'Moy.','stopwatch.avgLap':'Tour moyen','stopwatch.lap':'Tour','stopwatch.allLaps':'Tous les tours','dialog.updateImageTitle':'Mettre à jour l’image','resultDetail.totalTime':'Temps total','label.h':'h','label.m':'m','label.s':'s'
  };

  window.LocalesExtra['ru'] = {
    'title.app':'Ultimate Stopwatch','action.settings':'Настройки','action.close':'Закрыть','action.cancel':'Отмена','action.create':'Создать','action.save':'Сохранить','action.update':'Обновить','action.apply':'Применить','action.proceed':'Продолжить','action.resume':'Возобновить','action.pause':'Пауза','action.stop':'Стоп','action.reset':'Сброс','action.start':'Старт','action.next':'Далее','action.calculate':'Рассчитать','action.chooseImage':'Выбрать изображение','header.stopwatch':'Секундомер','home.empty1':'Проектов пока нет.','home.empty2':'Создайте проект, чтобы начать!','folder.empty1':'Результатов пока нет.','folder.empty2':'Начните измерение, чтобы создать!','folder.result':'результат','folder.results':'результатов','settings.language':'Язык','settings.units':'Единицы','settings.metric':'Метрические (мс, с)','settings.imperial':'Имперские','settings.currency':'Валюта','settings.power':'Питание','settings.keepAwake':'Держать экран включенным при зарядке','settings.timeDisplay':'Отображение времени','settings.hms':'Часы:Минуты:Секунды','settings.ms':'Минуты:Секунды','settings.precision':'Точность','settings.showHundredths':'Показывать сотые','settings.reOrContinue':'Перемерить или продолжить','settings.uploadChangeImage':'Загрузить/Сменить изображение','settings.projectSettings':'Настройки текущего проекта.','theme.title':'Настройка темы','theme.preset':'Предустановленные палитры','theme.customColors':'Пользовательские цвета','theme.background':'Фон','theme.accent':'Акцент','theme.text':'Текст','theme.border':'Граница','theme.applyCustom':'Применить тему','color.preset':'Предустановленные цвета','color.custom':'Пользовательский цвет','menu.chooseProjectColor':'Выбрать цвет проекта','menu.chooseProjectTextColor':'Выбрать цвет текста проекта','menu.delete':'Удалить','confirm.deleteProject':'Удалить этот проект и все его результаты?','confirm.deleteResult':'Удалить этот результат?','confirm.stopSession':'Остановить текущую сессию?','tooltip.newProject':'Новый проект','tooltip.startStopwatch':'Запустить секундомер','stopwatch.laps':'Круги','stopwatch.avg':'Средн.','stopwatch.avgLap':'Средний круг','stopwatch.lap':'Круг','stopwatch.allLaps':'Все круги','dialog.updateImageTitle':'Обновить изображение','resultDetail.totalTime':'Общее время','label.h':'ч','label.m':'м','label.s':'с'
  };

  window.LocalesExtra['da'] = {
    'title.app':'Ultimate Stopwatch','action.settings':'Indstillinger','action.close':'Luk','action.cancel':'Annuller','action.create':'Opret','action.save':'Gem','action.update':'Opdater','action.apply':'Anvend','action.proceed':'Fortsæt','action.resume':'Genoptag','action.pause':'Pause','action.stop':'Stop','action.reset':'Nulstil','action.start':'Start','action.next':'Næste','action.calculate':'Beregn','action.chooseImage':'Vælg billede','header.stopwatch':'Stoppur','home.empty1':'Ingen projekter endnu.','home.empty2':'Opret et for at komme i gang!','folder.empty1':'Ingen resultater endnu.','folder.empty2':'Start en måling for at oprette et!','folder.result':'resultat','folder.results':'resultater','settings.language':'Sprog','settings.units':'Enheder','settings.metric':'Metrisk (ms, s)','settings.imperial':'Imperial','settings.currency':'Valuta','settings.power':'Strøm','settings.keepAwake':'Hold skærmen tændt under opladning','settings.timeDisplay':'Tidsvisning','settings.hms':'Timer:Minutter:Sekunder','settings.ms':'Minutter:Sekunder','settings.precision':'Præcision','settings.showHundredths':'Vis hundrededele','settings.reOrContinue':'Mål igen eller fortsæt hvor du slap','settings.uploadChangeImage':'Upload/Skift billede','settings.projectSettings':'Projektindstillinger for det aktuelle projekt.','theme.title':'Tema-tilpasning','theme.preset':'Forudindstillede paletter','theme.customColors':'Brugerdefinerede farver','theme.background':'Baggrund','theme.accent':'Fremhævning','theme.text':'Tekst','theme.border':'Kant','theme.applyCustom':'Anvend tilpasset tema','color.preset':'Forudindstillede farver','color.custom':'Brugerdefineret farve','menu.chooseProjectColor':'Vælg projektfarve','menu.chooseProjectTextColor':'Vælg projektets tekstfarve','menu.delete':'Slet','confirm.deleteProject':'Slet dette projekt og alle dets resultater?','confirm.deleteResult':'Slet dette resultat?','confirm.stopSession':'Stop den aktuelle session?','tooltip.newProject':'Nyt projekt','tooltip.startStopwatch':'Start stoppur','stopwatch.laps':'Omgange','stopwatch.avg':'Gns.','stopwatch.avgLap':'Gns. omgang','stopwatch.lap':'Omgang','stopwatch.allLaps':'Alle omgange','dialog.updateImageTitle':'Opdater billede','resultDetail.totalTime':'Samlet tid','label.h':'t','label.m':'m','label.s':'s'
  };

  window.LocalesExtra['zh-Hans'] = {
    'title.app':'Ultimate Stopwatch','action.settings':'设置','action.close':'关闭','action.cancel':'取消','action.save':'保存','action.update':'更新','action.apply':'应用','action.proceed':'继续','action.calculate':'计算','action.chooseImage':'选择图片',
    'header.stopwatch':'秒表','home.empty1':'暂无项目。','home.empty2':'创建一个以开始！','folder.empty1':'暂无结果。','folder.empty2':'开始计时以创建结果！','folder.result':'结果','folder.results':'结果',
    'settings.language':'语言','settings.units':'单位','settings.metric':'公制（毫秒，秒）','settings.imperial':'英制','settings.currency':'货币','settings.power':'电源','settings.keepAwake':'充电时保持屏幕常亮','settings.timeDisplay':'时间显示','settings.hms':'小时:分钟:秒','settings.ms':'分钟:秒','settings.precision':'精度','settings.showHundredths':'显示百分之一秒','settings.reOrContinue':'重新测量或从上次继续','settings.uploadChangeImage':'上传/更换图片','settings.projectSettings':'当前项目的设置。',
    'theme.title':'主题自定义','theme.preset':'预设调色板','theme.customColors':'自定义颜色','theme.background':'背景','theme.accent':'强调色','theme.text':'文字','theme.border':'边框','theme.applyCustom':'应用自定义主题','color.preset':'预设颜色','color.custom':'自定义颜色',
    'menu.chooseProjectColor':'选择项目颜色','menu.chooseProjectTextColor':'选择文字颜色','menu.delete':'删除','confirm.deleteProject':'删除此项目及其所有结果？','confirm.deleteResult':'删除此结果？','confirm.stopSession':'停止当前会话？',
    'stopwatch.laps':'圈','stopwatch.avg':'平均','stopwatch.avgLap':'平均圈','stopwatch.lap':'圈','stopwatch.allLaps':'所有圈','calc.title':'计算','dialog.updateImageTitle':'更新图片','resultDetail.totalTime':'总时间',
    'tooltip.newProject':'新项目','tooltip.startStopwatch':'开始秒表','error.wakeLockUnsupported':'此浏览器不支持屏幕常亮。','error.saveFailed':'保存失败：存储已满或数据过大。','error.projectNotFound':'未找到项目，可能已删除。',
    'label.h':'时','label.m':'分','label.s':'秒','currency.euro':'欧元 (€)','currency.usd':'美元 ($)','currency.gbp':'英镑 (£)'
  };

  window.LocalesExtra['uk'] = {
    'title.app':'Ultimate Stopwatch','action.settings':'Налаштування','action.close':'Закрити','action.cancel':'Скасувати','action.save':'Зберегти','action.update':'Оновити','action.apply':'Застосувати','action.proceed':'Продовжити','action.calculate':'Обчислити','action.chooseImage':'Вибрати зображення',
    'header.stopwatch':'Секундомір','home.empty1':'Поки немає проєктів.','home.empty2':'Створіть, щоб розпочати!','folder.empty1':'Поки немає результатів.','folder.empty2':'Почніть вимірювання, щоб створити!','folder.result':'результат','folder.results':'результати',
    'settings.language':'Мова','settings.units':'Одиниці','settings.metric':'Метричні (мс, с)','settings.imperial':'Імперські','settings.currency':'Валюта','settings.power':'Живлення','settings.keepAwake':'Під час заряджання не вимикати екран','settings.timeDisplay':'Відображення часу','settings.hms':'Години:Хвилини:Секунди','settings.ms':'Хвилини:Секунди','settings.precision':'Точність','settings.showHundredths':'Показувати соті','settings.reOrContinue':'Перевиміряти або продовжити','settings.uploadChangeImage':'Завантажити/Змінити зображення','settings.projectSettings':'Налаштування поточного проєкту.',
    'theme.title':'Налаштування теми','theme.preset':'Стандартні палітри','theme.customColors':'Користувацькі кольори','theme.background':'Тло','theme.accent':'Акцент','theme.text':'Текст','theme.border':'Рамка','theme.applyCustom':'Застосувати власну тему','color.preset':'Стандартні кольори','color.custom':'Користувацький колір',
    'menu.chooseProjectColor':'Вибрати колір проєкту','menu.chooseProjectTextColor':'Вибрати колір тексту','menu.delete':'Видалити','confirm.deleteProject':'Видалити цей проєкт і всі результати?','confirm.deleteResult':'Видалити цей результат?','confirm.stopSession':'Зупинити поточну сесію?',
    'stopwatch.laps':'Кола','stopwatch.avg':'Середн.','stopwatch.avgLap':'Середнє коло','stopwatch.lap':'Коло','stopwatch.allLaps':'Усі кола','calc.title':'Обчислити','dialog.updateImageTitle':'Оновити зображення','resultDetail.totalTime':'Загальний час',
    'tooltip.newProject':'Новий проєкт','tooltip.startStopwatch':'Запустити секундомір','error.wakeLockUnsupported':'Wake Lock недоступний у цьому браузері.','error.saveFailed':'Не вдалося зберегти: сховище заповнене або дані надто великі.','error.projectNotFound':'Проєкт не знайдено. Можливо, його видалено.',
    'label.h':'г','label.m':'хв','label.s':'с','currency.euro':'Євро (€)','currency.usd':'Долар США ($)','currency.gbp':'Фунт (£)'
  };

  window.LocalesExtra['fi'] = {
    'title.app':'Ultimate Stopwatch','action.settings':'Asetukset','action.close':'Sulje','action.cancel':'Peruuta','action.save':'Tallenna','action.update':'Päivitä','action.apply':'Käytä','action.proceed':'Jatka','action.calculate':'Laske','action.chooseImage':'Valitse kuva',
    'header.stopwatch':'Sekuntikello','home.empty1':'Ei projekteja vielä.','home.empty2':'Luo projekti aloittaaksesi!','folder.empty1':'Ei tuloksia vielä.','folder.empty2':'Aloita mittaus luodaksesi!','folder.result':'tulos','folder.results':'tulosta',
    'settings.language':'Kieli','settings.units':'Yksiköt','settings.metric':'Metrinen (ms, s)','settings.imperial':'Imperial','settings.currency':'Valuutta','settings.power':'Virta','settings.keepAwake':'Pidä näyttö päällä latauksen aikana','settings.timeDisplay':'Ajan näyttö','settings.hms':'Tunnit:Minuutit:Sekunnit','settings.ms':'Minuutit:Sekunnit','settings.precision':'Tarkkuus','settings.showHundredths':'Näytä sadasosat','settings.reOrContinue':'Mittaa uudelleen tai jatka','settings.uploadChangeImage':'Lataa/Vaihda kuva','settings.projectSettings':'Nykyisen projektin asetukset.',
    'theme.title':'Teeman mukautus','theme.preset':'Esiasetetut paletit','theme.customColors':'Mukautetut värit','theme.background':'Tausta','theme.accent':'Korostus','theme.text':'Teksti','theme.border':'Reuna','theme.applyCustom':'Käytä mukautettua teemaa','color.preset':'Esiasetetut värit','color.custom':'Mukautettu väri',
    'menu.chooseProjectColor':'Valitse projektin väri','menu.chooseProjectTextColor':'Valitse tekstin väri','menu.delete':'Poista','confirm.deleteProject':'Poistetaanko tämä projekti ja sen kaikki tulokset?','confirm.deleteResult':'Poistetaanko tämä tulos?','confirm.stopSession':'Pysäytetäänkö nykyinen istunto?',
    'stopwatch.laps':'Kierrokset','stopwatch.avg':'Keskim.','stopwatch.avgLap':'Keskimääräinen kierros','stopwatch.lap':'Kierros','stopwatch.allLaps':'Kaikki kierrokset','calc.title':'Laske','dialog.updateImageTitle':'Päivitä kuva','resultDetail.totalTime':'Kokonaisaika',
    'tooltip.newProject':'Uusi projekti','tooltip.startStopwatch':'Käynnistä sekuntikello','error.wakeLockUnsupported':'Tämä selain ei tue Screen Wake Lockia.','error.saveFailed':'Tallennus epäonnistui: tallennustila täynnä tai data liian suurta.','error.projectNotFound':'Projektia ei löytynyt. Se on ehkä poistettu.',
    'label.h':'h','label.m':'min','label.s':'s','currency.euro':'Euro (€)','currency.usd':'Yhdysvaltain dollari ($)','currency.gbp':'Punta (£)'
  };

  window.LocalesExtra['sv'] = {
    'title.app':'Ultimate Stopwatch','action.settings':'Inställningar','action.close':'Stäng','action.cancel':'Avbryt','action.save':'Spara','action.update':'Uppdatera','action.apply':'Använd','action.proceed':'Fortsätt','action.calculate':'Beräkna','action.chooseImage':'Välj bild',
    'header.stopwatch':'Stoppur','home.empty1':'Inga projekt ännu.','home.empty2':'Skapa ett för att börja!','folder.empty1':'Inga resultat ännu.','folder.empty2':'Starta mätning för att skapa ett!','folder.result':'resultat','folder.results':'resultat',
    'settings.language':'Språk','settings.units':'Enheter','settings.metric':'Metriskt (ms, s)','settings.imperial':'Imperial','settings.currency':'Valuta','settings.power':'Ström','settings.keepAwake':'Håll skärmen på under laddning','settings.timeDisplay':'Tidsvisning','settings.hms':'Timmar:Minuter:Sekunder','settings.ms':'Minuter:Sekunder','settings.precision':'Precision','settings.showHundredths':'Visa hundradelar','settings.reOrContinue':'Mät igen eller fortsätt','settings.uploadChangeImage':'Ladda upp/Byt bild','settings.projectSettings':'Projektinställningar för aktuellt projekt.',
    'theme.title':'Temaanpassning','theme.preset':'Förinställda paletter','theme.customColors':'Anpassade färger','theme.background':'Bakgrund','theme.accent':'Accent','theme.text':'Text','theme.border':'Ram','theme.applyCustom':'Använd anpassat tema','color.preset':'Förinställda färger','color.custom':'Anpassad färg',
    'menu.chooseProjectColor':'Välj projektfärg','menu.chooseProjectTextColor':'Välj textfärg','menu.delete':'Ta bort','confirm.deleteProject':'Ta bort projektet och alla dess resultat?','confirm.deleteResult':'Ta bort detta resultat?','confirm.stopSession':'Stoppa den aktuella sessionen?',
    'stopwatch.laps':'Varv','stopwatch.avg':'Snitt','stopwatch.avgLap':'Snittvarv','stopwatch.lap':'Varv','stopwatch.allLaps':'Alla varv','calc.title':'Beräkna','dialog.updateImageTitle':'Uppdatera bild','resultDetail.totalTime':'Total tid',
    'tooltip.newProject':'Nytt projekt','tooltip.startStopwatch':'Starta stoppur','error.wakeLockUnsupported':'Wake Lock stöds inte i denna webbläsare.','error.saveFailed':'Det gick inte att spara: lagring full eller data för stora.','error.projectNotFound':'Projektet hittades inte. Det kan ha tagits bort.',
    'label.h':'t','label.m':'m','label.s':'s','currency.euro':'Euro (€)','currency.usd':'US-dollar ($)','currency.gbp':'Pund (£)'
  };

  window.LocalesExtra['ar'] = {
    'title.app':'Ultimate Stopwatch','action.settings':'الإعدادات','action.close':'إغلاق','action.cancel':'إلغاء','action.save':'حفظ','action.update':'تحديث','action.apply':'تطبيق','action.proceed':'متابعة','action.calculate':'حساب','action.chooseImage':'اختر صورة',
    'header.stopwatch':'ساعة إيقاف','home.empty1':'لا توجد مشاريع بعد.','home.empty2':'أنشئ مشروعًا للبدء!','folder.empty1':'لا توجد نتائج بعد.','folder.empty2':'ابدأ القياس لإنشاء نتيجة!','folder.result':'نتيجة','folder.results':'نتائج',
    'settings.language':'اللغة','settings.units':'الوحدات','settings.metric':'متري (مللي ثانية، ثانية)','settings.imperial':'إمبراطوري','settings.currency':'العملة','settings.power':'الطاقة','settings.keepAwake':'إبقاء الشاشة تعمل أثناء الشحن','settings.timeDisplay':'عرض الوقت','settings.hms':'ساعات:دقائق:ثوانٍ','settings.ms':'دقائق:ثوانٍ','settings.precision':'الدقة','settings.showHundredths':'إظهار أجزاء المئة','settings.reOrContinue':'إعادة القياس أو المتابعة','settings.uploadChangeImage':'رفع/تغيير الصورة','settings.projectSettings':'إعدادات المشروع الحالي.',
    'theme.title':'تخصيص السمة','theme.preset':'لوحات ألوان جاهزة','theme.customColors':'ألوان مخصصة','theme.background':'الخلفية','theme.accent':'التمييز','theme.text':'النص','theme.border':'الحدود','theme.applyCustom':'تطبيق سمة مخصصة','color.preset':'ألوان جاهزة','color.custom':'لون مخصص',
    'menu.chooseProjectColor':'اختر لون المشروع','menu.chooseProjectTextColor':'اختر لون نص المشروع','menu.delete':'حذف','confirm.deleteProject':'حذف هذا المشروع وجميع نتائجه؟','confirm.deleteResult':'حذف هذه النتيجة؟','confirm.stopSession':'إيقاف الجلسة الحالية؟',
    'stopwatch.laps':'لفات','stopwatch.avg':'متوسط','stopwatch.avgLap':'متوسط اللفة','stopwatch.lap':'لفة','stopwatch.allLaps':'كل اللفات','calc.title':'حساب','dialog.updateImageTitle':'تحديث الصورة','resultDetail.totalTime':'إجمالي الوقت',
    'tooltip.newProject':'مشروع جديد','tooltip.startStopwatch':'بدء ساعة الإيقاف','error.wakeLockUnsupported':'هذه المتصفح لا يدعم إبقاء الشاشة.','error.saveFailed':'فشل الحفظ: امتلأت المساحة أو البيانات كبيرة جدًا.','error.projectNotFound':'المشروع غير موجود. ربما تم حذفه.',
    'label.h':'س','label.m':'د','label.s':'ث','currency.euro':'يورو (€)','currency.usd':'دولار ($)','currency.gbp':'جنيه (£)'
  };

  window.LocalesExtra['hi'] = {
    'title.app':'Ultimate Stopwatch','action.settings':'सेटिंग्स','action.close':'बंद करें','action.cancel':'रद्द करें','action.save':'सहेजें','action.update':'अपडेट करें','action.apply':'लागू करें','action.proceed':'आगे बढ़ें','action.calculate':'गणना','action.chooseImage':'चित्र चुनें',
    'header.stopwatch':'स्टॉपवॉच','home.empty1':'अभी तक कोई प्रोजेक्ट नहीं।','home.empty2':'शुरू करने के लिए एक बनाएँ!','folder.empty1':'अभी तक कोई परिणाम नहीं।','folder.empty2':'परिणाम बनाने के लिए समय माप शुरू करें!','folder.result':'परिणाम','folder.results':'परिणाम',
    'settings.language':'भाषा','settings.units':'इकाइयाँ','settings.metric':'मीट्रिक (ms, s)','settings.imperial':'इम्पीरियल','settings.currency':'मुद्रा','settings.power':'पावर','settings.keepAwake':'चार्जिंग के दौरान स्क्रीन चालू रखें','settings.timeDisplay':'समय प्रदर्शन','settings.hms':'घं:मि:से','settings.ms':'मिनट:सेकंड','settings.precision':'सटीकता','settings.showHundredths':'हंड्रेड्थ दिखाएँ','settings.reOrContinue':'दोबारा मापें या जारी रखें','settings.uploadChangeImage':'अपलोड/छवि बदलें','settings.projectSettings':'वर्तमान प्रोजेक्ट की सेटिंग्स।',
    'theme.title':'थीम अनुकूलन','theme.preset':'पूर्वनिर्धारित पैलेट','theme.customColors':'कस्टम रंग','theme.background':'पृष्ठभूमि','theme.accent':'हाइलाइट','theme.text':'पाठ','theme.border':'बॉर्डर','theme.applyCustom':'कस्टम थीम लागू करें','color.preset':'पूर्वनिर्धारित रंग','color.custom':'कस्टम रंग',
    'menu.chooseProjectColor':'प्रोजेक्ट रंग चुनें','menu.chooseProjectTextColor':'पाठ रंग चुनें','menu.delete':'हटाएँ','confirm.deleteProject':'इस प्रोजेक्ट और उसके सभी परिणामों को हटाएँ?','confirm.deleteResult':'इस परिणाम को हटाएँ?','confirm.stopSession':'वर्तमान सत्र रोकें?',
    'stopwatch.laps':'लैप','stopwatch.avg':'औसत','stopwatch.avgLap':'औसत लैप','stopwatch.lap':'लैप','stopwatch.allLaps':'सभी लैप','calc.title':'गणना','dialog.updateImageTitle':'छवि अपडेट करें','resultDetail.totalTime':'कुल समय',
    'tooltip.newProject':'नया प्रोजेक्ट','tooltip.startStopwatch':'स्टॉपवॉच शुरू करें','error.wakeLockUnsupported':'यह ब्राउज़र स्क्रीन जागृत रखने का समर्थन नहीं करता।','error.saveFailed':'सहेजना विफल: स्टोरेज भरा है या डेटा बहुत बड़ा है।','error.projectNotFound':'प्रोजेक्ट नहीं मिला। शायद हटाया गया।',
    'label.h':'घं','label.m':'मि','label.s':'से','currency.euro':'यूरो (€)','currency.usd':'डॉलर ($)','currency.gbp':'पाउंड (£)'
  };

  window.LocalesExtra['bn'] = {
    'title.app':'Ultimate Stopwatch','action.settings':'সেটিংস','action.close':'বন্ধ','action.cancel':'বাতিল','action.save':'সংরক্ষণ','action.update':'আপডেট','action.apply':'প্রয়োগ','action.proceed':'চালিয়ে যান','action.calculate':'গণনা','action.chooseImage':'ছবি নির্বাচন করুন',
    'header.stopwatch':'স্টপওয়াচ','home.empty1':'এখনও কোনো প্রকল্প নেই।','home.empty2':'শুরু করতে একটি তৈরি করুন!','folder.empty1':'এখনও কোনো ফলাফল নেই।','folder.empty2':'ফলাফল তৈরি করতে সময় মাপা শুরু করুন!','folder.result':'ফলাফল','folder.results':'ফলাফল',
    'settings.language':'ভাষা','settings.units':'ইউনিট','settings.metric':'মেট্রিক (ms, s)','settings.imperial':'ইমপেরিয়াল','settings.currency':'মুদ্রা','settings.power':'পাওয়ার','settings.keepAwake':'চার্জিংয়ের সময় স্ক্রিন অন রাখুন','settings.timeDisplay':'সময় প্রদর্শন','settings.hms':'ঘন্টা:মিনিট:সেকেন্ড','settings.ms':'মিনিট:সেকেন্ড','settings.precision':'নির্ভুলতা','settings.showHundredths':'শতভাগ দেখান','settings.reOrContinue':'পুনরায় মাপুন বা চালিয়ে যান','settings.uploadChangeImage':'আপলোড/ছবি পরিবর্তন','settings.projectSettings':'বর্তমান প্রকল্পের সেটিংস।',
    'theme.title':'থিম কাস্টমাইজেশন','theme.preset':'প্রিসেট প্যালেট','theme.customColors':'কাস্টম রঙ','theme.background':'ব্যাকগ্রাউন্ড','theme.accent':'হাইলাইট','theme.text':'টেক্সট','theme.border':'বর্ডার','theme.applyCustom':'কাস্টম থিম প্রয়োগ','color.preset':'প্রিসেট রঙ','color.custom':'কাস্টম রঙ',
    'menu.chooseProjectColor':'প্রকল্পের রঙ নির্বাচন করুন','menu.chooseProjectTextColor':'টেক্সটের রঙ নির্বাচন করুন','menu.delete':'মুছে ফেলুন','confirm.deleteProject':'এই প্রকল্প এবং সব ফলাফল মুছবেন?','confirm.deleteResult':'এই ফলাফলটি মুছবেন?','confirm.stopSession':'বর্তমান সেশন বন্ধ করবেন?',
    'stopwatch.laps':'ল্যাপ','stopwatch.avg':'গড়','stopwatch.avgLap':'গড় ল্যাপ','stopwatch.lap':'ল্যাপ','stopwatch.allLaps':'সমস্ত ল্যাপ','calc.title':'গণনা','dialog.updateImageTitle':'ছবি আপডেট করুন','resultDetail.totalTime':'মোট সময়',
    'tooltip.newProject':'নতুন প্রকল্প','tooltip.startStopwatch':'স্টপওয়াচ শুরু করুন','error.wakeLockUnsupported':'এই ব্রাউজার স্ক্রিন অন রাখাকে সমর্থন করে না।','error.saveFailed':'সংরক্ষণ ব্যর্থ: স্টোরেজ পূর্ণ বা ডেটা বড়।','error.projectNotFound':'প্রকল্পটি পাওয়া যায়নি। সম্ভবত মুছে ফেলা হয়েছে।',
    'label.h':'ঘ','label.m':'মি','label.s':'সে','currency.euro':'ইউরো (€)','currency.usd':'ডলার ($)','currency.gbp':'পাউন্ড (£)'
  };

  window.LocalesExtra['ta'] = {
    'title.app':'Ultimate Stopwatch','action.settings':'அமைப்புகள்','action.close':'மூடு','action.cancel':'ரத்து செய்','action.save':'சேமி','action.update':'புதுப்பி','action.apply':'வினையாக்கு','action.proceed':'தொடர்','action.calculate':'கணக்கிடு','action.chooseImage':'படத்தை தேர்வுசெய்',
    'header.stopwatch':'ஸ்டாப்வாட்ச்','home.empty1':'இன்னும் திட்டங்கள் இல்லை.','home.empty2':'தொடங்க ஒன்றை உருவாக்கவும்!','folder.empty1':'இன்னும் முடிவுகள் இல்லை.','folder.empty2':'ஒரு முடிவை உருவாக்க நேரமிடலைத் தொடங்கவும்!','folder.result':'முடிவு','folder.results':'முடிவுகள்',
    'settings.language':'மொழி','settings.units':'அலகுகள்','settings.metric':'மெட்ரிக் (ms, s)','settings.imperial':'இம்பீரியல்','settings.currency':'நாணயம்','settings.power':'பவர்','settings.keepAwake':'சார்ஜிங் செய்யும் போது திரையை இயக்க வைத்திரு','settings.timeDisplay':'நேர காட்சி','settings.hms':'மணி:நிமிடம்:விநாடி','settings.ms':'நிமிடம்:விநாடி','settings.precision':'துல்லியம்','settings.showHundredths':'நூற்றில் ஒரு பகுதி காட்டவும்','settings.reOrContinue':'மீண்டும் அளவிட அல்லது தொடர','settings.uploadChangeImage':'பதிவேற்று/படத்தை மாற்று','settings.projectSettings':'தற்போதைய திட்டத்தின் அமைப்புகள்.',
    'theme.title':'தீம் தனிப்பயனாக்கம்','theme.preset':'முன்னமைக்கப்பட்ட பலேட்டுகள்','theme.customColors':'தனிப்பயன் நிறங்கள்','theme.background':'பின்புலம்','theme.accent':'உயர்வுப்புள்ளி','theme.text':'உரை','theme.border':'எல்லை','theme.applyCustom':'தனிப்பயன் தீமைக் கையாளு','color.preset':'முன்னமைக்கப்பட்ட நிறங்கள்','color.custom':'தனிப்பயன் நிறம்',
    'menu.chooseProjectColor':'திட்ட நிறத்தைத் தேர்ந்தெடு','menu.chooseProjectTextColor':'உரை நிறத்தைத் தேர்ந்தெடு','menu.delete':'அழி','confirm.deleteProject':'இந்த திட்டத்தையும் அதன் அனைத்து முடிவுகளையும் அழிக்கவா?','confirm.deleteResult':'இந்த முடிவை அழிக்கவா?','confirm.stopSession':'தற்போதைய அமர்வை நிறுத்தவா?',
    'stopwatch.laps':'சுற்றுகள்','stopwatch.avg':'சராசரி','stopwatch.avgLap':'சராசரி சுற்று','stopwatch.lap':'சுற்று','stopwatch.allLaps':'அனைத்து சுற்றுகள்','calc.title':'கணக்கிடு','dialog.updateImageTitle':'படத்தைப் புதுப்பி','resultDetail.totalTime':'மொத்த நேரம்',
    'tooltip.newProject':'புதிய திட்டம்','tooltip.startStopwatch':'ஸ்டாப்வாட்ச் தொடங்கு','error.wakeLockUnsupported':'இந்த உலாவி திரையை விழித்திருக்க ஆதரிக்காது.','error.saveFailed':'சேமித்தல் தோல்வியடைந்தது: சேமிப்பு நிரம்பியுள்ளது அல்லது தரவு பெரியது.','error.projectNotFound':'திட்டம் கிடைக்கவில்லை. அது நீக்கப்பட்டிருக்கலாம்.',
    'label.h':'ம','label.m':'நி','label.s':'வி','currency.euro':'யூரோ (€)','currency.usd':'டாலர் ($)','currency.gbp':'பவுண்ட் (£)'
  };

  // ADD_MORE_LOCALES_HERE
})();
